extends "res://tests/test_base.gd"
## Screenshots of UI and text-heavy screens in zh / ja (run under xvfb-run, without --headless).
func _initialize() -> void:
	_run()
func _run() -> void:
	await boot()
	for lang in ["zh", "ja"]:
		L.set_language(lang)
		G.new_game()
		await tick(3)
		await shot("loc_%s_c1_start" % lang)
		G.say_text(L.t("c1.intro"))
		await tick(3)
		await shot("loc_%s_c1_say" % lang)
		main.ask_pell(); await tick(4); await shot("loc_%s_hint" % lang)
		main._close_modal(); await tick(2)
		G.note("clock_fish"); G.note("floats"); G.note("shapes")
		main.open_notebook(); await tick(3); await shot("loc_%s_notebook" % lang)
		main._close_modal(); await tick(2)
		main.open_settings(); await tick(3); await shot("loc_%s_settings" % lang)
		main._close_modal(); await tick(2)
		main.open_pause(); await tick(3); await shot("loc_%s_pause" % lang)
		main._close_modal(); await tick(2)
		main.show_title(); await tick(4); await shot("loc_%s_title" % lang)
		main.title.queue_free(); main.title = null; main.modal = null; await tick(2)
		G.new_game(); await tick(2)
		main.open_album(); await tick(3); await shot("loc_%s_album" % lang)
		main._close_modal(); await tick(2)
		var es = load("res://game/core/end_screen.gd").new()
		main.overlay.add_child(es); es.setup("A"); await tick(30); await shot("loc_%s_end" % lang)
		es.queue_free(); await tick(2)
		var sp: Control = load("res://game/core/stage_player.gd").new()
		main.overlay.add_child(sp); sp.play(1)
		await tick(120); await shot("loc_%s_memory" % lang)
		sp.queue_free(); await tick(2)
	finish()
